[project]
name = "rag-for-legal-documents"
version = "0.1.0"
description = "Hybrid retrieval RAG system for legal contract Q&A"
authors = [
    {name = "gappy401",email = "nanditaghildyal@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml (>=6.0.3,<7.0.0)",
    "sentence-transformers (>=6.0.1,<7.0.0)",
    "faiss-cpu (>=1.15.0,<2.0.0)",
    "rank-bm25 (>=0.2.2,<0.3.0)",
    "anthropic (>=1.5.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.3.0,<8.0.0)",
    "jupyter (>=1.1.1,<2.0.0)"
]
